import { Language, ProductItem, RetailStorePresence, DistributionChannel } from '../types';

export const categoryTranslations: Record<Language, Record<string, string>> = {
  zh: {
    '休闲膨化': '休闲膨化',
    '烘焙饼干': '烘焙饼干',
    '果蔬脆片': '果蔬脆片',
    '养生休闲': '养生休闲',
    '有机坚果': '有机坚果',
    '大虾片系列': '大虾片系列 (真虾肉≥30%)',
    '糯米锅巴系列': '糯米锅巴系列 (咸蛋黄双面厚涂)',
    '威化系列': '优质威化系列 (新西兰奶源)',
    '小米锅巴': '原粮小米锅巴',
    '五黑山药脆片': '五黑滋补山药脆片',
    '红薯片': '原切低油红薯脆片',
    '山楂制品': '原果打浆山楂零食',
    '薯类制品': '双色脆脆薯条',
    '苏打饼干': '二次慢发酵苏打饼干',
    '进口品牌代理 · 国际烘焙': '进口代理 · 丹麦皇家黄油曲奇',
    '进口品牌代理 · 奢华黑金': '进口代理 · 瑞士进口巧克力曲奇',
    '进口品牌代理 · 果酱曲奇': '进口代理 · 真实果酱流心曲奇',
    '进口品牌代理 · 便捷小食': '进口代理 · 商超便利便携装',
    '进口品牌代理 · 纯净健康': '进口代理 · 苏格兰无麸质纯燕麦',
    '进口品牌代理 · 英伦经典': '进口代理 · 英国麦维他黑巧消化饼',
  },
  en: {
    '休闲膨化': 'Puffed Snacks',
    '烘焙饼干': 'Baked Biscuits & Crackers',
    '果蔬脆片': 'Fruit & Veggie Crisps',
    '养生休闲': 'Wellness & Tonic Snacks',
    '有机坚果': 'Organic Nuts & Kernels',
    '大虾片系列': 'Jumbo Shrimp Crisps (≥30% Real Shrimp)',
    '糯米锅巴系列': 'Glutinous Rice Crisps (Double Salted Egg Yolk)',
    '威化系列': 'Premium Wafer Biscuits (NZ Milk Solids)',
    '小米锅巴': 'Natural Millet Crisps',
    '五黑山药脆片': 'Five-Black Tonic Yam Slices',
    '红薯片': 'Natural Sweet Potato Chips',
    '山楂制品': 'Pure Hawthorn Berry Bites',
    '薯类制品': 'Crispy Dual-Potato Sticks',
    '苏打饼干': 'Slow Fermented Soda Crackers',
    '进口品牌代理 · 国际烘焙': 'Imported Agency · Royal Danish Butter Cookies',
    '进口品牌代理 · 奢华黑金': 'Imported Agency · Swiss Chocolate Cookies',
    '进口品牌代理 · 果酱曲奇': 'Imported Agency · Real Fruit Jam Center Cookies',
    '进口品牌代理 · 便捷小食': 'Imported Agency · CVS & Grab-and-Go Packs',
    '进口品牌代理 · 纯净健康': 'Imported Agency · Scottish Gluten-Free Oats',
    '进口品牌代理 · 英伦经典': 'Imported Agency · British Dark Choco Digestives',
  },
  vi: {
    '休闲膨化': 'Snack phồng tôm & giòn tan',
    '烘焙饼干': 'Bánh quy & Bánh nướng',
    '果蔬脆片': 'Rau củ quả sấy giòn',
    '养生休闲': 'Ăn vặt bổ dưỡng sức khỏe',
    '有机坚果': 'Hạt dẻ hữu cơ Organic',
    '大虾片系列': 'Bánh phồng tôm đại (≥30% tôm thật)',
    '糯米锅巴系列': 'Cơm cháy nếp giòn (Trứng muối phủ 2 mặt)',
    '威化系列': 'Bánh quế xốp Wafer (Sữa New Zealand)',
    '小米锅巴': 'Cơm cháy kê vàng truyền thống',
    '五黑山药脆片': 'Khoai mài giòn bổ dưỡng ngũ hắc',
    '红薯片': 'Khoai lang giòn sấy chân không VF',
    '山楂制品': 'Kẹo sơn tra tự nhiên nguyên chất',
    '薯类制品': 'Khoai tây que giòn hai màu',
    '苏打饼干': 'Bánh quy Soda lên men tự nhiên',
    '进口品牌代理 · 国际烘焙': 'Đại lý nhập khẩu · Bánh quy bơ Hoàng gia Đan Mạch',
    '进口品牌代理 · 奢华黑金': 'Đại lý nhập khẩu · Bánh quy socola Thụy Sĩ',
    '进口品牌代理 · 果酱曲奇': 'Đại lý nhập khẩu · Bánh quy nhân mứt trái cây',
    '进口品牌代理 · 便捷小食': 'Đại lý nhập khẩu · Gói tiện lợi bán lẻ CVS',
    '进口品牌代理 · 纯净健康': 'Đại lý nhập khẩu · Yến mạch nguyên cám Scotland',
    '进口品牌代理 · 英伦经典': 'Đại lý nhập khẩu · Bánh quy lúa mì socola Anh',
  },
  ja: {
    '休闲膨化': 'スナック・おこげせんべい',
    '烘焙饼干': '焼き菓子・クッキー・クラッカー',
    '果蔬脆片': '野菜・フルーツクリスプチップス',
    '养生休闲': '薬食同源・健康スナック',
    '有机坚果': 'オーガニック有機ナッツ・甘栗',
    '大虾片系列': '特大エビせんべい (エビ含有量≥30%)',
    '糯米锅巴系列': 'もち米おこげ (塩卵黄ダブルコーティング)',
    '威化系列': '特製ウエハース (NZ産ミルク)',
    '小米锅巴': '天然アワおこげせんべい',
    '五黑山药脆片': '五黒山芋クリスプチップス',
    '红薯片': '厚切りさつまいもチップス',
    '山楂制品': '果肉仕立てサンザシロール',
    '薯类制品': 'ツインポテトスティック',
    '苏打饼干': '長時間熟成発酵ソーダクラッカー',
    '进口品牌代理 · 国际烘焙': '正規代理 · デンマーク風バタークッキー',
    '进口品牌代理 · 奢华黑金': '正規代理 · スイスチョコプレミアムクッキー',
    '进口品牌代理 · 果酱曲奇': '正規代理 · 果実ジャムクッキー',
    '进口品牌代理 · 便捷小食': '正規代理 · コンビニ・レジ横スナック',
    '进口品牌代理 · 纯净健康': '正規代理 · スコットランド産グルテンフリーオート麦',
    '进口品牌代理 · 英伦经典': '正規代理 · 英国伝統ダークチョコビスケット',
  },
  ko: {
    '休闲膨化': '스낵 칩 & 누룽지',
    '烘焙饼干': '베이커리 쿠키 & 크래커',
    '果蔬脆片': '과일 및 야채 바삭칩',
    '养生休闲': '약식동원 웰빙 스낵',
    '有机坚果': '유기농 견과 & 맛밤',
    '大虾片系列': '대형 새우칩 (생새우살 함유량 ≥30%)',
    '糯米锅巴系列': '찹쌀 누룽지 (생오리알노른자 더블 코팅)',
    '威化系列': '프리미엄 웨이퍼 (뉴질랜드산 원유)',
    '小米锅巴': '조 누룽지 바삭 스낵',
    '五黑山药脆片': '오흑 마 건강 스낵칩',
    '红薯片': '원물 그대로 바삭 고구마칩',
    '山楂制品': '생과즙 산사 롤 & 바이트',
    '薯类制品': '투톤 바삭 감자스틱',
    '苏打饼干': '천연 저온 숙성 발효 소다 크래커',
    '进口品牌代理 · 国际烘焙': '공식 수입 대행 · 덴마크 왕실풍 버터 쿠키',
    '进口品牌代理 · 奢华黑金': '공식 수입 대행 · 스위스 초콜릿 쿠키',
    '进口品牌代理 · 果酱曲奇': '공식 수입 대행 · 리얼 과일잼 쿠키',
    '进口品牌代理 · 便捷小食': '공식 수입 대행 · 편의점 및 소포장 스낵',
    '进口品牌代理 · 纯净健康': '공식 수입 대행 · 스코틀랜드 글루텐프리 오트밀',
    '进口品牌代理 · 英伦经典': '공식 수입 대행 · 영국 맥비티 다크초코 다이제스티브',
  },
  ar: {
    '休闲膨化': 'المقرمشات المنفوخة ورقائق الأرز',
    '烘焙饼干': 'بسكويت المخبوزات والكوكيز',
    '果蔬脆片': 'رقائق الفواكه والخضار المقرمشة',
    '养生休闲': 'سناكس صحية ومغذية',
    '有机坚果': 'مكسرات وكستناء عضوية',
    '大虾片系列': 'رقائق الروبيان الفاخرة (روبيان حقيقي ≥30%)',
    '糯米锅巴系列': 'مقرمشات الأرز الدبق بصفار البيض المملح',
    '威化系列': 'بسكويت الويفر الفاخر بحليب نيوزيلندا',
    '小米锅巴': 'مقرمشات الدخن الطبيعية',
    '五黑山药脆片': 'رقائق اليام المغذية',
    '红薯片': 'رقائق البطاطا الحلوة المقرمشة',
    '山楂制品': 'لفائف الزعرور الطبيعية',
    '薯类制品': 'أصابع البطاطس المزدوجة المقرمشة',
    '苏打饼干': 'بسكويت الصودا المخمر طبيعياً',
    '进口品牌代理 · 国际烘焙': 'وكالة حصرية · كوكيز الزبدة الدنماركية الملكية',
    '进口品牌代理 · 奢华黑金': 'وكالة حصرية · كوكيز الشوكولاتة السويسرية',
    '进口品牌代理 · 果酱曲奇': 'وكالة حصرية · كوكيز بمربى الفواكه الحقيقية',
    '进口品牌代理 · 便捷小食': 'وكالة حصرية · عبوات التجزئة الفردية',
    '进口品牌代理 · 纯净健康': 'وكالة حصرية · شوفان اسكتلندي خالٍ من الغلوتين',
    '进口品牌代理 · 英伦经典': 'وكالة حصرية · بسكويت الشوكولاتة الداكنة البريطاني',
  },
  th: {
    '休闲膨化': 'ขนมขบเคี้ยวพองกรอบ',
    '烘焙饼干': 'บิสกิตอบกรอบและคุกกี้',
    '果蔬脆片': 'ผักและผลไม้อบกรอบ VF',
    '养生休闲': 'ขนมขบเคี้ยวเพื่อสุขภาพ',
    '有机坚果': 'ถั่วและเกาลัดออร์แกนิก',
    '大虾片系列': 'ข้าวเกรียบกุ้งจัมโบ้ (เนื้อกุ้งแท้ ≥30%)',
    '糯米锅巴系列': 'ข้าวตังข้าวเหนียวกรอบไข่เค็มเคลือบสองด้าน',
    '威化系列': 'เวเฟอร์ระดับพรีเมียม (นมนำเข้านิวซีแลนด์)',
    '小米锅巴': 'ข้าวตังข้าวฟ่างธรรมชาติ',
    '五黑山药脆片': 'มันเทศจีนแผ่นอบกรอบเพื่อสุขภาพ',
    '红薯片': 'มันหวานแท้ทอดสุญญากาศ VF',
    '山楂制品': 'ฮอว์ธอร์นบดธรรมชาติ',
    '薯类制品': 'มันฝรั่งแท่งกรอบสองสี',
    '苏打饼干': 'แครกเกอร์โซดาหมักธรรมชาติสองขั้นตอน',
    '进口品牌代理 · 国际烘焙': 'ตัวแทนนำเข้าหลัก · คุกกี้เนยสไตล์เดนมาร์ก IMPERIAL',
    '进口品牌代理 · 奢华黑金': 'ตัวแทนนำเข้าหลัก · คุกกี้ช็อกโกแลตสวิส',
    '进口品牌代理 · 果酱曲奇': 'ตัวแทนนำเข้าหลัก · คุกกี้ไส้แยมผลไม้แท้',
    '进口品牌代理 · 便捷小食': 'ตัวแทนนำเข้าหลัก · ซองพกพาสะดวกสำหรับ CVS',
    '进口品牌代理 · 纯净健康': 'ตัวแทนนำเข้าหลัก · ข้าวโอ๊ตกลูเตนฟรีสกอตแลนด์',
    '进口品牌代理 · 英伦经典': 'ตัวแทนนำเข้าหลัก · บิสกิตไดเจสทีฟดาร์กช็อกโกแลตอังกฤษ',
  },
};

export const localizedStoreData: Record<
  Language,
  Record<
    string,
    {
      storeName: string;
      location: string;
      date: string;
      type: string;
      highlight: string;
      channelCategory: string;
      shelfTag: string;
    }
  >
> = {
  zh: {
    'gz-grandbuy': {
      storeName: '广州市 · 广百广场 (天河中怡店)',
      location: '广东省广州市天河区天河路200号',
      date: '实拍存证：2024.01.04 20:43',
      type: '大型精品百货超市端头礼盒大堆头',
      highlight: 'IMPERIAL 皇家丹麦曲奇礼盒大堆头、高端进口食品专柜全品类铺市，节庆礼盒重点展区',
      channelCategory: 'KA核心百货商超',
      shelfTag: '百货精品超市端头',
    },
    'handan-melody': {
      storeName: '邯郸市 · 美乐城超市 (进口世界商品专区)',
      location: '河北省邯郸市丛台区人民东路美乐城',
      date: '实拍存证：2026.04.21 10:23',
      type: '“世界商品 WORLD GOODS” 进口零食专柜',
      highlight: 'IMPERIAL 经典蓝罐曲奇、红盒果酱曲奇与比利时饼干并列黄金展位，现货明码标价热销',
      channelCategory: '大型综合购物中心超市',
      shelfTag: '世界商品专区',
    },
    'quyang-xinyulou': {
      storeName: '保定市 · 信誉楼百货 (曲阳店)',
      location: '河北省保定市曲阳县商业步行街',
      date: '实拍存证：2026.01.01 09:01',
      type: '中岛环形红色蓝色铁盒双立柱节日堆头',
      highlight: '现场专业理货团队督导巡展，整箱陈列与礼盒展销，日均动销突破数千盒',
      channelCategory: '区域龙头连锁百货',
      shelfTag: '中岛双立柱大堆头',
    },
    'national-boutique': {
      storeName: '全国高端精品超市 (Ole\' / BLT / 盒马X会员)',
      location: '北京 / 上海 / 深圳 / 广州 / 杭州',
      date: '常态化在架销售',
      type: '国际烘焙及健康零食标杆货架',
      highlight: '涵盖苏格兰 Nairn\'s 无麸质燕麦、英国 McVitie\'s 麦维他、欧洲烘焙精品全系排面',
      channelCategory: '高端会员制与精品零售',
      shelfTag: '进口烘焙精品货架',
    },
  },
  en: {
    'gz-grandbuy': {
      storeName: 'Guangzhou · Grandbuy Plaza (Tianhe Zhongyi Store)',
      location: 'No. 200 Tianhe Road, Tianhe District, Guangzhou, China',
      date: 'On-site Audit: 2024.01.04 20:43',
      type: 'Department Store Endcap & Island Gift Display',
      highlight: 'Massive IMPERIAL Royal Danish Cookies island display, high-visibility positioning during major festival shopping peaks',
      channelCategory: 'Top-tier KA Department Store',
      shelfTag: 'Department Store Endcap',
    },
    'handan-melody': {
      storeName: 'Handan · Melody City Hypermarket (World Goods Section)',
      location: 'Renmin East Road, Congtai District, Handan, Hebei, China',
      date: 'On-site Audit: 2026.04.21 10:23',
      type: '"WORLD GOODS" Imported Confectionery Aisle',
      highlight: 'IMPERIAL classic blue tin & red jam cookies holding prime eye-level shelves alongside premium European imports',
      channelCategory: 'Mega Shopping Mall Hypermarket',
      shelfTag: 'World Goods Imported Zone',
    },
    'quyang-xinyulou': {
      storeName: 'Baoding · Xinyulou Department Store (Quyang Branch)',
      location: 'Commercial Pedestrian Street, Quyang County, Baoding, China',
      date: 'On-site Audit: 2026.01.01 09:01',
      type: 'Dual-Column Island Display with Red & Blue Tins',
      highlight: 'Dedicated Tefeeo in-store merchandisers overseeing pallet-level stacking and high festive turnover exceeding 1,000 tins/day',
      channelCategory: 'Regional Flagship Department Chain',
      shelfTag: 'Dual-Pillar Pallet Display',
    },
    'national-boutique': {
      storeName: 'Nationwide Boutique Retail (Ole\' / BLT / Freshippo X-Club)',
      location: 'Beijing / Shanghai / Shenzhen / Guangzhou / Hangzhou',
      date: 'Permanent Shelving Distribution',
      type: 'International Bakery & Health Snack Endcaps',
      highlight: 'Full portfolio distribution of Scottish Nairn\'s gluten-free oats, British McVitie\'s digestives, and European baked treats',
      channelCategory: 'Premium Membership & Boutique Retail',
      shelfTag: 'Imported Premium Snack Aisles',
    },
  },
  vi: {
    'gz-grandbuy': {
      storeName: 'Quảng Châu · TTTM Grandbuy Plaza (Chi nhánh Tianhe)',
      location: 'Số 200 Đường Tianhe, Quận Tianhe, Quảng Châu, TQ',
      date: 'Kiểm toán thực tế: 2024.01.04 20:43',
      type: 'Đảo trưng bày hộp quà tại siêu thị bách hóa lớn',
      highlight: 'Đảo trưng bày bánh quy hoàng gia Đan Mạch IMPERIAL quy mô lớn, vị trí vàng trong mùa mua sắm lễ hội',
      channelCategory: 'Đại siêu thị bách hóa KA',
      shelfTag: 'Đầu kệ siêu thị cao cấp',
    },
    'handan-melody': {
      storeName: 'Hàm Đan · Siêu thị Melody City (Khu hàng nhập khẩu quốc tế)',
      location: 'Đường Nhân Dân Đông, Quận Tùng Đài, Hàm Đan, Hà Bắc, TQ',
      date: 'Kiểm toán thực tế: 2026.04.21 10:23',
      type: 'Kệ bánh kẹo nhập khẩu "WORLD GOODS"',
      highlight: 'Bánh quy hộp thiếc xanh IMPERIAL và bánh mứt đỏ chiếm vị trí tầm mắt vàng, tốc độ bán ra ấn tượng',
      channelCategory: 'Đại siêu thị phức hợp mua sắm',
      shelfTag: 'Khu hàng quốc tế',
    },
    'quyang-xinyulou': {
      storeName: 'Bảo Định · Bách hóa Xinyulou (Chi nhánh Khúc Dương)',
      location: 'Phố đi bộ thương mại, Huyện Khúc Dương, Bảo Định, TQ',
      date: 'Kiểm toán thực tế: 2026.01.01 09:01',
      type: 'Đảo trưng bày trụ đôi hộp thiếc xanh và đỏ',
      highlight: 'Đội ngũ giám sát bán hàng chuyên nghiệp của Tefeeo túc trực, doanh số tiêu thụ dịp lễ vượt hàng nghìn hộp/ngày',
      channelCategory: 'Chuỗi bách hóa đầu ngành khu vực',
      shelfTag: 'Đảo trưng bày trụ đôi',
    },
    'national-boutique': {
      storeName: 'Hệ thống siêu thị cao cấp toàn quốc (Ole\' / BLT / Hema X)',
      location: 'Bắc Kinh / Thượng Hải / Thâm Quyến / Quảng Châu / Hàng Châu',
      date: 'Phân phối liên tục thường xuyên',
      type: 'Kệ chuẩn bánh kẹo & đồ ăn nhẹ nhập khẩu',
      highlight: 'Phân phối toàn diện yến mạch Nairn\'s Scotland, bánh McVitie\'s Anh Quốc và đồ nướng châu Âu',
      channelCategory: 'Bán lẻ cao cấp & thành viên VIP',
      shelfTag: 'Kệ bánh kẹo nhập khẩu',
    },
  },
  ja: {
    'gz-grandbuy': {
      storeName: '広州市 · 広百広場 (天河中怡店)',
      location: '広東省広州市天河区天河路200号',
      date: '実地検証記録：2024.01.04 20:43',
      type: '大型百貨店スーパーのエンド＆アイランド特設コーナー',
      highlight: 'IMPERIALデンマークバタークッキーの巨大タワー陳列、祝祭日ギフトシーズンの重点プロモーション展開',
      channelCategory: 'KA中核百貨店スーパー',
      shelfTag: '百貨店エンド陳列',
    },
    'handan-melody': {
      storeName: '邯鄲市 · メロディーシティスーパー (輸入商品専門フロア)',
      location: '河北省邯鄲市叢台区人民東路',
      date: '実地検証記録：2026.04.21 10:23',
      type: '「WORLD GOODS」輸入スナック専用コーナー',
      highlight: 'IMPERIAL定番ブルー缶クッキーとジャムクッキーがヨーロッパ名門菓子と並ぶゴールデンゾーンを確保',
      channelCategory: '大型総合ショッピングセンター',
      shelfTag: '輸入ワールド商品エリア',
    },
    'quyang-xinyulou': {
      storeName: '保定市 · 信誉楼百貨店 (曲陽店)',
      location: '河北省保定市曲陽県商業歩行街',
      date: '実地検証記録：2026.01.01 09:01',
      type: 'センターアイランド型赤青缶ツインタワー陳列',
      highlight: '特菲奥専属マーチャンダイザーによる定期巡回と補充、祝祭期は1日1,000缶以上の驚異的販売実績',
      channelCategory: '地域有力大手百貨店チェーン',
      shelfTag: 'アイランド特大タワー陳列',
    },
    'national-boutique': {
      storeName: '全国プレミアム高級スーパー (Ole\' / BLT / フーマーX会員)',
      location: '北京 / 上海 / 深セン / 広州 / 杭州',
      date: '常時店頭陳列・販売中',
      type: '輸入ベーカリー＆健康スナック旗艦棚',
      highlight: 'スコットランドNairn\'sグルテンフリーオーツ、英国McVitie\'sなど名門輸入菓子を全面展開',
      channelCategory: '高級会員制スーパー＆セレクトショップ',
      shelfTag: '輸入高級ベーカリー棚',
    },
  },
  ko: {
    'gz-grandbuy': {
      storeName: '광저우시 · 광바이 플라자 (톈허 중이점)',
      location: '광둥성 광저우시 톈허구 톈허로 200',
      date: '현장 실사 인증: 2024.01.04 20:43',
      type: '대형 백화점 슈퍼마켓 엔드캡 및 아일랜드 매대',
      highlight: 'IMPERIAL 덴마크 버터쿠키 대형 아일랜드 매대, 명절 선물 쇼핑 시즌 압도적 매출',
      channelCategory: '핵심 KA 백화점 마트',
      shelfTag: '백화점 마트 엔드캡',
    },
    'handan-melody': {
      storeName: '한단시 · 멜로디 시티 마트 (세계 수입식품 코너)',
      location: '허베이성 한단시 충타이구 인민동로',
      date: '현장 실사 인증: 2026.04.21 10:23',
      type: '"WORLD GOODS" 수입 제과 전문 매대',
      highlight: 'IMPERIAL 시그니처 블루틴 버터쿠키와 레드 과일잼 쿠키가 골든존 차지',
      channelCategory: '대형 복합 쇼핑몰 마트',
      shelfTag: '세계 수입식품 구역',
    },
    'quyang-xinyulou': {
      storeName: '바오딩시 · 신위러우 백화점 (취양점)',
      location: '허베이성 바오딩시 취양현 상업 보행자거리',
      date: '현장 실사 인증: 2026.01.01 09:01',
      type: '아일랜드 듀얼 레드/블루 틴 캔 타워 진열',
      highlight: 'Tefeeo 전담 슈퍼바이저 현장 진열 관리, 명절 성수기 일일 1,000캔 이상 판매 돌파',
      channelCategory: '지역 선두 체인 백화점',
      shelfTag: '아일랜드 듀얼 타워 매대',
    },
    'national-boutique': {
      storeName: '전국 프리미엄 부티크 마트 (Ole\' / BLT / 허마 X회원)',
      location: '베이징 / 상하이 / 선전 / 광저우 / 항저우',
      date: '상시 매대 진열 및 판매',
      type: '글로벌 베이커리 & 건강 스낵 표준 매대',
      highlight: '스코틀랜드 Nairn\'s 글루텐프리 오트, 영국 McVitie\'s 다이제스티브 전 라인업 입점',
      channelCategory: '프리미엄 회원제 & 럭셔리 유통',
      shelfTag: '수입 프리미엄 베이커리 매대',
    },
  },
  ar: {
    'gz-grandbuy': {
      storeName: 'قوانغتشو · ساحة غوانغ باي (فرع تيانهي)',
      location: 'رقم 200 طريق تيانهي، قوانغتشو، الصين',
      date: 'تدقيق ميداني: 2024.01.04 20:43',
      type: 'منصة عرض هدايا كبرى في متجر متعدد الأقسام',
      highlight: 'منصة عرض كبرى لكوكيز الزبدة الملكية الدنماركية IMPERIAL بموقع متميز خلال مواسم الأعياد',
      channelCategory: 'متاجر كبرى رئيسية KA',
      shelfTag: 'رأس رف المتجر الكبير',
    },
    'handan-melody': {
      storeName: 'هان دان · سوبرماركت ميلودي سيتي (قسم المنتجات العالمية)',
      location: 'طريق رينمين الشرقي، منطقة كونغتاي، هاندان، الصين',
      date: 'تدقيق ميداني: 2026.04.21 10:23',
      type: 'ممر الحلويات المستوردة "WORLD GOODS"',
      highlight: 'كوكيز IMPERIAL بالعلب الزرقاء الشهيرة تحتل الرفوف الأكثر وضوحاً في القسم الدولي',
      channelCategory: 'مركز تسوق ضخم',
      shelfTag: 'قسم السلع العالمية المستوردة',
    },
    'quyang-xinyulou': {
      storeName: 'باودينغ · متجر شين يو لوه (فرع تشويانغ)',
      location: 'شارع المشاة التجاري، تشويانغ، باودينغ، الصين',
      date: 'تدقيق ميداني: 2026.01.01 09:01',
      type: 'منصة عرض مزدوجة للعلب الحمراء والزرقاء',
      highlight: 'إشراف ميداني مستمر من مشرفي Tefeeo مع مبيعات قياسية تتجاوز ألف علبة يومياً في الأعياد',
      channelCategory: 'سلسلة متاجر تجزئة إقليمية رائدة',
      shelfTag: 'منصة عرض مزدوجة',
    },
    'national-boutique': {
      storeName: 'سلاسل التجزئة الفاخرة في عموم الصين (Ole\' / BLT / Freshippo)',
      location: 'بكين / شنغهاي / شنتشن / قوانغتشو / هانغتشو',
      date: 'توزيع وتواجد دائم على الرفوف',
      type: 'أرفف المخبوزات والوجبات الخفيفة الصحية العالمية',
      highlight: 'توزيع شامل لمنتجات الشوفان الاسكتلندي Nairn\'s ومخبوزات McVitie\'s البريطانية',
      channelCategory: 'متاجر تجزئة فاخرة وعضوية مميزة',
      shelfTag: 'أرفف المخبوزات المستوردة الفاخرة',
    },
  },
  th: {
    'gz-grandbuy': {
      storeName: 'กวางโจว · แกรนด์บาย พลาซ่า (สาขาเทียนเหอ จงยี่)',
      location: 'เลขที่ 200 ถนนเทียนเหอ เขตเทียนเหอ กวางโจว ประเทศจีน',
      date: 'การตรวจสอบจริง: 2024.01.04 20:43',
      type: 'แท่นวางกล่องของขวัญหัวเกาะห้างสรรพสินค้าชั้นนำ',
      highlight: 'แท่นวางคุกกี้เนยสไตล์เดนมาร์ก IMPERIAL ขนาดใหญ่ โดดเด่นในช่วงเทศกาลจับจ่าย',
      channelCategory: 'ห้างสรรพสินค้าชั้นนำ KA',
      shelfTag: 'หัวเกาะห้างสรรพสินค้า',
    },
    'handan-melody': {
      storeName: 'หานตาน · ซูเปอร์มาร์เก็ต เมโลดี้ ซิตี้ (โซนสินค้านำเข้าจากทั่วโลก)',
      location: 'ถนนเหรินหมินตะวันออก เขตฉงไถ หานตาน เหอเป่ย์ ประเทศจีน',
      date: 'การตรวจสอบจริง: 2026.04.21 10:23',
      type: 'โซนขนมขบเคี้ยวนำเข้า "WORLD GOODS"',
      highlight: 'คุกกี้กระป๋องสีน้ำเงินคลาสสิก IMPERIAL และคุกกี้แยมแดง ครองตำแหน่งสายตาระดับทอง',
      channelCategory: 'ซูเปอร์มาร์เก็ตในศูนย์การค้าครบวงจร',
      shelfTag: 'โซนสินค้านำเข้าระดับโลก',
    },
    'quyang-xinyulou': {
      storeName: 'เป่าติ้ง · ห้างสรรพสินค้า ซินอวี้โหลว (สาขาชวี่หยาง)',
      location: 'ถนนคนเดินพาณิชย์ อำเภอชวี่หยาง เป่าติ้ง เหอเป่ย์ ประเทศจีน',
      date: 'การตรวจสอบจริง: 2026.01.01 09:01',
      type: 'แท่นวางเสาคู่ทรงกลมกระป๋องเหล็กสีแดงและน้ำเงิน',
      highlight: 'ทีมจัดเรียงสินค้ามืออาชีพของ Tefeeo ดูแลอย่างใกล้ชิด ยอดขายช่วงเทศกาลทะลุพันกล่องต่อวัน',
      channelCategory: 'เครือข่ายห้างสรรพสินค้าชั้นนำระดับภูมิภาค',
      shelfTag: 'แท่นวางเสาคู่ทรงเกาะ',
    },
    'national-boutique': {
      storeName: 'ซูเปอร์มาร์เก็ตพรีเมียมระดับประเทศ (Ole\' / BLT / Freshippo X)',
      location: 'ปักกิ่ง / เซี่ยงไฮ้ / เซินเจิ้น / กวางโจว / หางโจว',
      date: 'วางจำหน่ายเป็นประจำบนชั้นวาง',
      type: 'ชั้นวางเบเกอรี่และของว่างเพื่อสุขภาพชั้นนำระดับโลก',
      highlight: 'ครอบคลุมข้าวโอ๊ต Nairn\'s จากสกอตแลนด์ บิสกิต McVitie\'s จากอังกฤษ และเบเกอรี่ยุโรปชั้นนำ',
      channelCategory: 'ค้าปลีกระดับพรีเมียมและระบบสมาชิก',
      shelfTag: 'ชั้นวางเบเกอรี่นำเข้าพรีเมียม',
    },
  },
};

export const getLocalizedStore = (
  store: RetailStorePresence,
  lang: Language
): RetailStorePresence => {
  const storeLangMap = localizedStoreData[lang] || localizedStoreData['en'] || localizedStoreData['zh'];
  const localized = storeLangMap[store.id];
  if (!localized) return store;

  return {
    ...store,
    ...localized,
  };
};

export const getLocalizedCategory = (category: string, lang: Language): string => {
  const langMap = categoryTranslations[lang] || categoryTranslations['en'] || categoryTranslations['zh'];
  return langMap[category] || category;
};
